export const TabaDAOLogo = () => {
  return (
    <svg
      viewBox="0 0 120 120"
      className="h-10 w-10"
      xmlns="http://www.w3.org/2000/svg"
      aria-label="Logotipo Sóbrio e Integrado - Versão Contorno Branco"
    >
      <g>
        <line
          x1="100"
          y1="60"
          x2="88.28"
          y2="88.28"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="100"
          cy="60"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="100"
          y2="60"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="88.28"
          y1="88.28"
          x2="60"
          y2="100"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="88.28"
          cy="88.28"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="88.28"
          y2="88.28"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="60"
          y1="100"
          x2="31.71"
          y2="88.28"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="60"
          cy="100"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="60"
          y2="100"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="31.71"
          y1="88.28"
          x2="20"
          y2="60"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="31.71"
          cy="88.28"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="31.71"
          y2="88.28"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="20"
          y1="60"
          x2="31.71"
          y2="31.71"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="20"
          cy="60"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="20"
          y2="60"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="31.71"
          y1="31.71"
          x2="60"
          y2="20"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="31.71"
          cy="31.71"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="31.71"
          y2="31.71"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="60"
          y1="20"
          x2="88.28"
          y2="31.71"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="60"
          cy="20"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="60"
          y2="20"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>
        <line
          x1="88.28"
          y1="31.71"
          x2="100"
          y2="60"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></line>
        <circle
          cx="88.28"
          cy="31.71"
          r="5"
          fill="#FFFFFF"
          stroke="#FFFFFF"
          strokeWidth="1"
        ></circle>
        <line
          x1="60"
          y1="60"
          x2="88.28"
          y2="31.71"
          stroke="#FFFFFF"
          strokeWidth="1"
          strokeDasharray="2"
        ></line>

        <path
          d="M60,30 Q60,60 90,60 T60,90 Q60,60 30,60 T60,30 Z"
          fill="none"
          stroke="#FFFFFF"
          strokeWidth="2"
        ></path>
        <circle cx="60" cy="60" r="8" fill="none" />
      </g>
    </svg>
  );
};
