name: APIs
on: [push, pull_request]
jobs:
  lint-and-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npm run apis:lint
      - run: npm run apis:docs
      - uses: actions/upload-artifact@v4
        with: { name: defy-api-docs, path: docs/defy-api.html }
