NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

WEB_AUTH_ENDPOINT="http://localhost:8082/auth"
TRANSFER_SERVER_SEP0024="http://localhost:8082/sep24"
KYC_SERVER="http://localhost:8082/sep12"

[[CURRENCIES]]
code="BRLD"
issuer="GCXWBWKZC22G3DR6IJVYFHMNET4KC2MPXZAGHG2HOQZGJAGLYLW356UV"
status="test"
display_decimals=2

[[CURRENCIES]]
code="USDC"
issuer="GCXWBWKZC22G3DR6IJVYFHMNET4KC2MPXZAGHG2HOQZGJAGLYLW356UV"
status="test"
display_decimals=2
