NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
SIGNING_KEY="<G...publica_da_SIGNING_SEED>"
WEB_AUTH_ENDPOINT="http://localhost:8081/auth"
KYC_SERVER="http://localhost:8081/kyc"
TRANSFER_SERVER_SEP0024="http://localhost:8081/sep24"
ANCHOR_QUOTE_SERVER="http://localhost:8081/sep38"

ACCOUNTS=["GCXWBWKZC22G3DR6IJVYFHMNET4KC2MPXZAGHG2HOQZGJAGLYLW356UV"]

[[CURRENCIES]]
code="BRLD"
issuer="GCXWBWKZC22G3DR6IJVYFHMNET4KC2MPXZAGHG2HOQZGJAGLYLW356UV"
display_decimals=2
contract="CCUZQJDBHXZ5W3GMX4GG2EWN4OKQ6SCHMVOIB6W6TQLVUKEV5ZPCWUTH"
status="test"
